project:
  type: website
  output-dir: docs

website:
  title: "Quarto"
  navbar:
    background: "dark"
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - Labs.qmd
      - Projects.qmd
      - Presentations.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

