project:
  type: website
  output-dir: docs

website:
  title: "Quarto"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - sidebar:labs
      - Projects.qmd
      - Presentations.qmd
  sidebar: 
    -id:labs
      title:"Labs"
      style: "docked"
      background: "light"
      collapse-level:1
      contents:
        Bio676Labs.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

