---
title: "AuFond"
author: "John Bauer"
---

**Au Fond des temps pt 1 by Valentin Clastrier**

After three days of rain, the clouds abated. The rain slicked road's golden 
hue lay below a blanket of mist, undisturbed but for the occasional drop from 
the rooftops. The city's streets were empty of traffic at 2am and quiet as a 
grave. Their footsteps echoed among the brick and concrete warehouses on 
either side. As they moved forward, the pavement sparkled under the 
incandescent light of the lamp light above. The whole street was aglow, paved 
in orange gold. The likes of which no king could dream. Only the shadow of 
their shadow revealed its true dull gray nature. Looking up at the streetlamps 
above them, they could see no stars behind the yellow clouds that still held 
the threat of rain. The lamps themselves were enshrined in misty halos. While 
the lamp's diffused light safely painted the path before them, the buildings 
on either side of them were enshrouded in darkness. The lamp's liquid gold 
could only go so far before being swallowed by alleyways and dark doorways. 
The intractable shadows made them nervous. Their mind populating the unknown 
with a thousand terrifying things lurking in the darkness. The thought kept 
them from the center of the road as they passed through the silent industrial 
tableau. The rusty machinery laying forgotten outside a factory cast grotesque 
shadows on its walls. The monstrous shape crawled across bricks as they walked 
as if they themselves were the source of light. They quickened their pace to 
put the eerie dance behind them. For the next few minutes, they kept their 
eyes on the radiant path before them, focusing on the magnificent shifting 
waves of golden streetlight before them. But it was not long before their eyes 
returned to gazing into the shadows in the gaps between buildings and behind 
dirty glass windows. 

The old man was sitting so still the figure walking down 
the street almost missed him. It was not until his face turned to look as 
theirs that the man's visage jumped into stark relief. The glow of the 
streetlamps deepened every crease in the man's weathered face. The hair 
framing his face stuck to his skin unmoved by the earlier rain. His beard was 
wild, and his eyes pierced the night into their soul. His gaze drew the breath 
from their lungs. The intense look he gave spoke of a life hard lived. Of a 
hundred quiet indignities and a thousand loud ones. Of desperation, fear, and 
anger. His eyes searched the figure for something amorphous. Scouring every 
part of their body. The shadows drawn by lamplight held no secrets from him. 
The figure felt raw and naked beneath his stare, perpetually vulnerable. All 
of this was felt in an instance before the old man broke eye contact to adjust 
the blue tarp that covered him. Turning his shoulder into the eave protecting 
him, the fire in his eye faded. When he returned his eyes to the figure, they 
reflected the dull glow of the streetlights. The figure, suddenly free of 
their paralysis, started walking down the street, ever conscious of the weight 
of the old man's eyes on their shoulders. 

Long after they turned the corner they shivered.
