---
title: "ClairedeLune"
author: "John Bauer"
---


**Claire de Lune by Isao Tomita**

```{r, echo=FALSE,message=FALSE, warning=FALSE}
library(shinyLP)
```

<iframe width="560" height="315" src="https://www.youtube.com/embed/773dDn0PM8E?si=oiG8lovwwVEnHxfX" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

Everyone was waiting outside the airlock when Lune finally arrived. The team barely acknowledges them once they took their place at the back of the room. They all stood with a boredom that only comes endless repetition. Maq gave them a terse nod from their position next to the airlock hatch leaning against the inside of the hull. They were all fidgeting in different ways to pass the time before the ships made contact. Lapu check the ports of the portable generator by their feet despite knowing they had just been replaced last time they made berth. Kahlu kept opening the center clasp of the heavy backpack forcing them to lean backwards against the wall. Faren was standing in front of airlock controls rhythmically tapping the sides of their thighs to the tune of a song.

The large metallic clang and the accompanying reverberations of the ships collision ended their boredom. Maq raised their eyebrows at Lune before uncrossing their arms and standing ready before the airlock port. Lapu and Kahlu shouldered their loads and fell into place behind Maq while Faren saw to the opening of the airlock.

With the docking clamps engaged, Faren began their survey of the abandoned ship's environment. After a few moments spent tapping on the console, Faren announced "No need for masks, the air is passable. Little light on the oxygen side, but breathable."

"Any biologics flying around?" asked Maq. Lapu grinned back at Lune. Rolling their eyes and nodding towards Maq who still facing the hatch. Lapu mouthed "worry wort" back at Lune. After a few more taps on the console screen, Faren answered "There's little to no organic material in the air, shouldn't be a problem."

"I'd rather not take that chance." said Maq. "Who knows how long the ship's fans have been dormant. Everybody seal up."

With everyone's helmets in place. Maq's voice came over the comms, "Enough dawdling, let's go."

They grasp the door handle. The dull iron latch is smooth and cold to the touch. The light from the port hole illuminates their arm and chest as they turn the latch. Gears whir, mechanisms click, and the sealed door locks disengage. They push the door open aided by the corridor's warm air gently that blows past them. The door is ajar, but they look back down the hallway dim, warm and dusty, before pushing through into the room. All at once, the hull of the ship drops away from them. The majesty of the universe, the burning reds and yellows of stars and the purple and green of unborn stars cradled in their nebulas all laid bare before them. The sheer size of it all is awful in both definitions of the word. They cling to the wall and gape at the viewing bubble. It's as if nothing is there, no curve of a glass wall, nor the quiet hum of a hull shield. The lack of boundaries is as inviting as it is terrifying. They feel as if they're standing on the edge of a cliff. The floor of the viewing bubble appears to top a meter away from the door, but the room walls continue for another meter. They take a deep breath and venture forth. The first step off the dull grey metal is taken with deep hesitation. The nothingness that they stepped out on is firm and quickly dispels any fear they held with their breast. It is in this moment when the fear has left them, that they truly look at the universe. It is an intricate tableau. Distant stars dust the scene with clusters of red dwarfs burning brightly. Clouds of purple and green mix in a brilliant cosmic soup or like spirits frozen in a dance. The stars closer to the ship glitter like inlaid gems in a crown. They take another step out into the nothingness and any attachments to the rest of the group, the world they came from, and the species they belong to us severed. They float among the stars, adrift amongst the light of a thousand ancient stars. They do not feel small in this vastness, but one with a greater organism in the void.
