---
title: "Gifted"
author: "John Bauer"
---

**Gifted by Cristobal Tapia de Veer**

The grizzled old man scratched his chin. He hauls on the cord and the motor sputters to life. With a terse grunt, he kicks 
off the dock to set the boat free in the river. The syncopated hum of the engine grows suddenly loud as the 
boat gets up to speed.

The landscape before you is eerily still. The glassy water ahead is broken only by the prow of the boat. The grey sky tinged with the dull orange of the setting sun is reflected in its mirror. As the river narrows, the swampy shores become so dense with foliage they seem to trap all light in their depths.

The old man slows the boat. The river is so narrow now that reeds rasp against the hull. The way forward seems too small to continue, but once around a bend it opens broadly into a small lake. The old man's eyes are transfixed on the shacks lit by torches on the opposite end. The boat picks up speed. Its humming once again hitting in slow waves.

Halfway across the lake the wooded shacks come into focus. The wood is old and worn. A few shacks have remnants of paint clinging to the beams providing the only color to this otherwise greyscale scene. Even the people appear grey. They line the shores and dock silently staring at the incoming boat. 

The boat's engine grows loud in your ear. 
Why don't they move? 
The boat glides up to the dock. 
Why don't they speak?  
The man at the end of the dock leans down with his torch and pulls 
the boat closer.
Why can't I leave? 
