---
title: "GodsinHeat"
author: "John Bauer"
---

**Gods in Heat by TOBACCO**

```{r, echo=FALSE,message=FALSE, warning=FALSE}
library(shinyLP)
```

<iframe width="560" height="315" src="https://www.youtube.com/embed/4zLVnDf0W_U?si=_fntjaT5zVvgKav_" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

The dense heat of the jungle clung to his damp skin. The circuitous path before him was crisscrossed in low hanging vines and leaves. Roots of gigantic trees interwove into a treacherous tapestry of undergrowth. Each one of his steps was carefully chosen to avoid their nooks. His eyes were so fixed on the ground that he frequently was slapped in the face by the oily undersides of gigantic leaves.

The sounds of the jungle had long left. Not a single bird proclaimed their presence. No lemur could be heard chattering to their compatriots. Even the incessant buzzing of insects had ceased its din. A lone spider resting amidst its web hanging from a leaf was the only sign of fauna he had seen in an hour. It was like an evacuation order had been issued to the jungle. 

Suddenly the web shook as a low basey noise sounded through the jungle. Another beat quickly followed the first. The startled spider fled its web to the safety of the alcove between the trunk and leaf above its web. Only its long legs could be seen. 

He raised his eyes towards the path before him. The now steady beats seemed to be rumbling from ahead of him, muffled by the dense foliage. He hefted his pack and resumed his trek. The path began to straighten before him. Where gnarled tree trunks blocked his view, now there was broken granite stones leading up an incline fenced in by trees that had grown so densely that their trunks had fused together to form walls of twisting vines.

The beats were getting louder with every step. As he reached the base of the stones another instrument join the rhythm. The strange notes crawled up his skin and beckoned him to climb like running lights on an airstrip. The granite stones were too shaped to be natural he realized. They must be long forgotten stairs. Years of rain and sunshine had caused them to shift and sink, slowly entombing them in roots.

The inviting music could be resisted no longer. He began to climb the ancient staircase. The view that greeted him as he crested was that of a large clearing full of more granite chunks sticking out at odd angles from tall grass swaying in time with the music.

The music was emanating from the large stone structure at its center. Its melody was no longer muted by the trees and struck his body in waves. The harmonic undertow pulled him forward towards the center structure. The details of the structure became clearer as he neared. The center structure was the torso of a gigantic being intricately carve with geometric designs so worn by time they gave the being's granite skin a wavy look. Its three arms were buried nearby up to their elbows. Stood before the immense towering torso, he felt inconsequential. The music pouring out of nine holes in its chest now set his hair on end at this distance. Awed, he took the pack off his sweaty back and sat cross legged before the giant.

Suddenly, fierce light blazed from the holes, each a different color as the music swelled. New instruments joined the fray and a great rumbling in the ground beneath began to shake his very atoms. The chunks of granite he walked past began to pull themselves from the soft earth and float towards the torso. Each piece fit effortlessly into place without making a noise. Only the melody issuing from its chest could be heard.

Reassembled, the granite being slowly got to its feet. Its three arms broke the earth and pushed the giant to its feet. At its true height, the lights now flashed and spun, weaving their spotlights amongst the tall grass. And then, the giant being began to dance...

Each footfall rattle the entire jungle to the beat. Its three arms wave through the air in long undulating motions as its torso rotated freely. It swayed with the grace of the long grass below it. Over and over again, its swaying brought its granite visage looming over him. It was if it was peering at a slow moving insect on the jungle floor.

The beats ceased and the melody began to slow the dramatic swaying of the granite being became lethargic. A chuck of its fore arm fell abruptly to the ground, followed by another from its knee. Soon giant chunks of granite rained from above him. The giant's puppeteer was clipping its strings and the magic that held the being together receded with the music. The torso was the last to fall, gently lowering into the ground as the last beats faded. The glow of the nine holes dimmed and left him once again along in the clearing.