---
title: "Hill Curve"
author: "John Bauer"
date: "2024-06-19"
output: html_document
---
```{r, echo=FALSE,message=FALSE,warning=FALSE}
library(tidyverse)
library(ggplot2)
library(scales)

```

```{r}
hillscale_x <-scale_x_log10(labels = label_log(digits = 2), limits=c(10**-3, 10**1), breaks=log_breaks(n=5), guide = guide_axis_logticks(long = 3, mid = 2, short = 1))
hillscale_y <-scale_y_log10(labels = label_log(digits = 2), limits=c(10**-4, 10**2), breaks=log_breaks(n=7), guide = guide_axis_logticks(long = 3, mid = 2, short = 1))


```

```{py}

```



```{r Import Data}
flowdata <-read.csv("~/Bio 676/Quarto/AndrewsLab/HillCurve/example_input_data.csv")
```

```{r Regression Line}
if sys.argv[1] not in ['help', '-h', '-help', '--help']:
    data_file = sys.argv[1]
else:
    print(__doc__)
    sys.exit(0)
Kd_ubound = int(sys.argv[2]) if sys.argv[2].lower() != 'inf' else np.inf
n_ubound = int(sys.argv[3]) if sys.argv[3].lower() != 'inf' else np.inf
ymin_guess = int(sys.argv[4]) if sys.argv[4].lower() != 'none' else 1
ymax_guess = int(sys.argv[5]) if sys.argv[5].lower() != 'none' else 1
outfile = sys.argv[6] + '.csv'



hill <- function(x, Kd, n, ymin, ymax){
   ymin + (ymax - ymin) * (x**n) / (Kd**n + x**n)} # Linear scale
hill_log <- function(x, Kd, n, ymin, ymax){
   log10(ymin + (ymax - ymin) * (x**n) / (Kd**n + x**n))} # Log scale
hill_res <- function(params, ind_conc, exp_val){
    #Calculate the Hill Equation residuals on a linear scale.
    Kd = params[0]
    n = params[1]
    ymin = params[2]
    ymax = params[3]
    rpu = ymin + (ymax - ymin) * (ind_conc**n) / (Kd**n + ind_conc**n)
    return(rpu - exp_val)}
hill_res_log <-function(params, ind_conc, exp_val){
    #Calculate the Hill Equation residuals on a log scale.
    Kd = params[0]
    n = params[1]
    ymin = params[2]
    ymax = params[3]
    log_rpu = log10(ymin + (ymax - ymin) * (ind_conc**n) / (Kd**n + ind_conc**n))
    log_exp = log10(exp_val)
    return(log_rpu - log_exp)}
```

```{r}
params0 <- c(0.1, 1, 1, 1)
res_lsq_lin_log10 <- least_squares(hill_res_log, params0, args = (inducer_conc, RPU), bounds = (0, [Kd_ubound, n_ubound, np.inf, np.inf]))
print(f'For the linear least_squares function using a log scale for residuals,\nKd = {res_lsq_lin_log10.x[0]}, n = {res_lsq_lin_log10.x[1]}, ymin = {res_lsq_lin_log10.x[2]}, ymax = {res_lsq_lin_log10.x[3]}')
```


```{r Plot Data}
flowdata %>%
  ggplot(aes(x=Inducer_conc,y=RPU_avg))+geom_point()+hillscale_x+hillscale_y+theme_classic()+labs(x="Inducer Concentration", y="RPU")+geom_errorbar(aes(ymin=RPU_avg-RPU_sd,ymax=RPU_avg+RPU_sd))
```

